version: '3'
services:
  trivia:
    image: chanzer0/media-server-trivia:latest
    build: .
    ports:
      - "${HOST_PORT:-8080}:${HOST_PORT:-8080}"
    environment:
      - PLEX_BASE_URL=${PLEX_BASE_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - FLASK_RUN_PORT=${HOST_PORT:-8080}
