"""Constants for the media server trivia app."""

# Cache settings
CACHE_CLEANUP_INTERVAL = 300  # 5 minutes
CACHE_MAX_AGE_DAYS = 7
CACHE_MAX_SIZE_MB = 1000

# Video processing settings
DEFAULT_SAMPLE_RATE = 200
MIN_SAMPLE_RATE = 50
TARGET_FRAME_SAMPLES = 300
VIDEO_BACKEND_TIMEOUT = 5

# Session management
SESSION_TIMEOUT_SECONDS = 600  # 10 minutes
SESSION_CLEANUP_INTERVAL = 60  # 1 minute
MAX_CONCURRENT_SESSIONS = 10

# API settings
DEFAULT_CAST_LIMIT = 12
MAX_MOVIE_OPTIONS = 4

# Frame processing
FRAME_RESIZE_WIDTH = 160
COLOR_QUANTIZATION_COLORS = 5
MIN_COLOR_PERCENTAGE = 0.05

# Framed game settings
FRAMED_ROUNDS = 7
FRAMED_FRAME_WIDTH = 1280
FRAMED_FRAME_HEIGHT = 720
FRAMED_CACHE_DIR = "cache/framed_frames"

# Cast Match game settings
CAST_MATCH_ROUNDS = 4
CAST_MATCH_MIN_MOVIES = 2
CAST_MATCH_MAX_MOVIES = 5
CAST_MATCH_CACHE_DIR = "cache/cast_match"

# Quote game settings
QUOTE_ROUNDS = 5
QUOTE_MIN_LENGTH = 30
QUOTE_MAX_LENGTH = 200